### ISSUE TITLE
/say @e blocked but not /console @e

### ISSUE THREAD

**Issue by veast-mUJ9bDjOlP** [kaboomserver/extras#10]
As the title says, say @e is blocked but not console @e.

Proof:
https://user-images.githubusercontent.com/68193060/104830934-9c36f080-587b-11eb-9ccb-53d24b31cd7f.mp4

**Comment by mathiascode** [comment]
See https://github.com/kaboomserver/extras/commit/1adb54013a80556fb7d2698d41d3db8df9657e82
