### ISSUE TITLE
Spawnpoint with any axis value of 2147483647 crashes server instantly

### ISSUE THREAD

**Issue by business-goose** [kaboomserver/extras#16]

**Comment by business-goose** [comment]
Or, by extension, any command able to teleport the player to 2147483647+

**Comment by business-goose** [comment]
bump

**Comment by mathiascode** [comment]
> Or, by extension, any command able to teleport the player to 2147483647+

Shouldn't this be covered by https://github.com/kaboomserver/extras/blob/master/src/main/java/pw/kaboom/extras/modules/entity/EntityTeleport.java already?

**Comment by business-goose** [comment]
> > Or, by extension, any command able to teleport the player to 2147483647+
> 
> Shouldn't this be covered by https://github.com/kaboomserver/extras/blob/master/src/main/java/pw/kaboom/extras/modules/entity/EntityTeleport.java already?

Since this is an issue precluding spawnpoints instead of entity teleportation, it isn't covered by [EntityTeleport.java](https://github.com/kaboomserver/extras/blob/master/src/main/java/pw/kaboom/extras/modules/entity/EntityTeleport.java).

**Comment by mathiascode** [comment]
I've always considered ServerCommand.java a rather ugly, last-resort method of fixing issues, that shouldn't really exist in the first place. Time has shown that these superficial command patches are rather easily bypassed, e.g. by using command signs, which ultimately had to be disabled. I'd like to avoid imposing limits on every command due to some specific ones malfunctioning.

I'd check if there are any events to hook into that could be used to fix this issue. I could do this as well, if you provide a persistent way of reproducing the issue.

**Comment by business-goose** [comment]
> I've always considered ServerCommand.java a rather ugly, last-resort method of fixing issues, that shouldn't really exist in the first place. Time has shown that these superficial command patches are rather easily bypassed, e.g. by using command signs, which ultimately had to be disabled. I'd like to avoid imposing limits on every command due to some specific ones malfunctioning.
> 
> I'd check if there are any events to hook into that could be used to fix this issue. I could do this as well, if you provide a persistent way of reproducing the issue.

How to reproduce this issue:

1. Set your spawnpoint to a position with 2147483647 as a coordinate on any axis.
2. Respawn
3. Wait a few seconds for the server to freak out

In my experience you can change the location of where a player by listenining for PlayerRespawnEvent (this plugin is for beta 1.7.3, it may now be asynchronous). But I think in this instance it will be beneficial to catch this before the spawnpoint is set since I think the server will error out before Extras has the chance to set the spawnpoint (might not be true, untested).
