### ISSUE TITLE
Option to randomize spawn location

### ISSUE THREAD

**Issue by ayunami2000** [kaboomserver/extras#309]
and an option to enable randomization of spawn on every join instead of just the first one. also randomizes respawn location on death. per player

**Comment by allinkdev** [comment]
I Agree Kind Sir

**Comment by allinkdev** [comment]
Should probably be noted that this can degrade the server in modern versions of Minecraft due to how unoptimized chunk generation is. As such, this should be off by default, and a warning should be provided.
