### ISSUE TITLE
[ISSUE] If allow join on full server is off, but join restrictions are disabled, players can still join on full server

### ISSUE THREAD

**Issue by ayunami2000** [kaboomserver/extras#312]
[see problematic line here](https://github.com/kaboomserver/extras/blob/5e12d92010d1441f8732174d014d3d8396428d5b/src/main/java/pw/kaboom/extras/modules/player/PlayerConnection.java#L93)

**Comment by allinkdev** [comment]
Isn't this intended functionality?
