### ISSUE TITLE
Disable /jfr as it can crash servers in 10 seconds and everyone can just turn on their hacked client and start spamming jfr start jfr stop

### ISSUE THREAD

**Issue by mirkokral** [kaboomserver/extras#343]
title

**Comment by allinkdev** [comment]
![image](https://user-images.githubusercontent.com/44676012/229497051-032e65da-e689-4b2d-92e7-294a832954e6.png)

The command in question is not enabled on Kaboom, due to the server using a minimal JDK which does not include the Java Flight Recorder.

**Comment by mirkokral** [comment]
then mcslot problem
