### ISSUE TITLE
Extras' skin command upon invoking the command teleports you into a parallel limbo world

### ISSUE THREAD

**Issue by business-goose** [kaboomserver/extras#9]
This occurs on any client below 1.16.x (vanilla and otherwise, these are vanilla clients however it shows up as 3rd party due to my usage of MultiMC). This may be an issue with ViaBackwards, however this limbo behavior has occurred on Waterfall proxy servers for quite some time now.

Behavior in this limbo is as follows:

1. Changing your yaw is completely broken, and instead jitters back and forth very quickly.
2. You are unable to move
3. You can see mobs and players
4. You can still hold items

![image](https://user-images.githubusercontent.com/44676012/103875107-e83ea400-50c9-11eb-9b34-4e7750ec766d.png)
![image](https://user-images.githubusercontent.com/44676012/103875251-191ed900-50ca-11eb-9e64-46ff303a85ec.png)

**Comment by TFTWPhoenix** [comment]
I noticed this while working on my client. Would be nice to see it fixed =)

**Comment by mathiascode** [comment]
I'll look into it this weekend.

**Comment by mathiascode** [comment]
Fixed in the latest versions of ViaVersion/ViaBackwards.
